apiVersion: apps/v1
kind: Deployment
metadata:
  name: finecollectionservice
  namespace: {{ .Values.namespace }}
  labels:
    app: finecollectionservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finecollectionservice
  template:
    metadata:
      labels:
        app: finecollectionservice
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "finecollectionservice"
        dapr.io/app-port: "6001"
        dapr.io/config: "dapr-config"
    spec:
      containers:
      - name: finecollectionservice
        image: bbdemo1.azurecr.io/finecollectionservice:latest
        ports:
        - containerPort: 6001
        env:
          - name: USE_KUBERNETES_SECRETS
            value: "true"
      imagePullSecrets:
      - name: bbdemo1secret  
      