apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mosquitto
    version: v1
  name: mosquitto
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
        - name: mosquitto
          image: bbdemo1.azurecr.io/mosquitto:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 1883
      restartPolicy: Always
      imagePullSecrets:
      - name: bbdemo1secret
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: mosquitto
  name: mosquitto
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: "mqtt"
    port: 1883
    targetPort: 1883
  selector:
    app: mosquitto

