apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulation
  namespace: {{ .Values.namespace }}
  labels:
    app: simulation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulation
  template:
    metadata:
      labels:
        app: simulation
    spec:
      containers:
      - name: simulation
        image: bbdemo1.azurecr.io/simulation:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: MQTT_HOST
            value: mosquitto.dapr-trafficcontrol.svc.cluster.local
      imagePullSecrets:
      - name: bbdemo1secret