apiVersion: apps/v1
kind: Deployment
metadata:
  name: trafficcontrolservice
  namespace: {{ .Values.namespace }}
  labels:
    app: trafficcontrolservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trafficcontrolservice
  template:
    metadata:
      labels:
        app: trafficcontrolservice
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "trafficcontrolservice"
        dapr.io/app-port: "6000"
        dapr.io/config: "dapr-config"
    spec:
      containers:
      - name: trafficcontrolservice
        image: bbdemo1.azurecr.io/trafficcontrolservice:latest
        ports:
        - containerPort: 6000
        imagePullPolicy: IfNotPresent
      imagePullSecrets:
      - name: bbdemo1secret
 